### ISSUE TITLE
Snap to grid / Snap to Guide

### ISSUE THREAD

**Issue by raphaelbastide** [glyphr-studio/Glyphr-Studio-1#140]
As we already have a modular grid it could be useful for many projects to have “snap to the grid”option in the project settings or a toggle button on the drawing interface. I think it is not the same as #13 right?

**Comment by mattlag** [comment]
This existed, but maybe it got closed with some other grid work.  Snap to grid is definitely useful.  Also snap to guide line.

**Comment by TuxVisual92** [comment]
Hi, I can't find this feature, will it be implemented?

**Comment by mattlag** [comment]
No plan as of right now.  Individual x/y coordinates can be locked - so if you want a point to 'stick' to a certain x coordinate, just set it in the attributes panel and select the lock icon in the input box.

This will happen eventually, but it's not being worked on right now.

**Comment by mattlag** [comment]
This is implemented, will probably be pushed soon to the online site in v1.13
