### ISSUE TITLE
Importing 'News Cycle' font creates a char 0x17FT

### ISSUE THREAD

**Issue by mattlag** [glyphr-studio/Glyphr-Studio-1#159]
That's not Hex.

**Comment by davelab6** [comment]
CC @n8willis

**Comment by mattlag** [comment]
Mostly this is for me, at the moment Glyphr Studio only can deal with glyphs that have a unicode representation.  This was while importing a SVG Font, right now I check to see if a character's unicode is within a certain range and filter some out, and due to some bug, this hex value slipped through the cracks.

**Comment by davelab6** [comment]
Is this the newscycle from GFD?

**Comment by mattlag** [comment]
Yes, except I then sent it through some online converter to make it into a SVG Font.  This was part of testing Glyphr Studio's SVG Font import/export features.

Possibly the SVG Font was generated poorly, or I put a typo in there at some point, but this is the cause: it's a ft ligature:

```
<glyph glyph-name="longs_t" unicode="&#x17f;t" horiz-adv-x="994" d="..." />
```
the ;t shouldn't be there.

**Comment by davelab6** [comment]
The version in GFD is old... Font squirrel converter?

**Comment by mattlag** [comment]
I used http://onlinefontconverter.com/ - although since then, it has become quite horrible (UI wise).

I didn't really care about the version, I just needed a bunch of SVG Fonts for import testing :-)

**Comment by n8willis** [comment]
Well, I can verify that longs_t is set to u+fb05 in News Cycle; it's a discretionary ligature for longs (u+017f) + t (u+0074). To me, that suggests that the converter may be tripping up on parsing "longs_t" -- squishing the +017f from "longs" into the "t" itself.

**Comment by mattlag** [comment]
Cool, I figured it may have been the OTF to SVG conversion.  I need to look for mal-formed unicode stuff in my Glyphr Studio code, regardless.

**Comment by mattlag** [comment]
Better hex / svg sniffing in v1.08
