### ISSUE TITLE
Move Import SVG window into Chooser panel

### ISSUE THREAD

**Issue by davelab6** [glyphr-studio/Glyphr-Studio-1#188]
Currently there is an `Import SVG` item in the main Glyphr menu:

![screen shot 2015-05-09 at 4 29 05 am](https://cloud.githubusercontent.com/assets/261579/7548504/f6f6d7d2-f603-11e4-812a-2bd0669b1428.png)

And in the leftmost sidebar of 2 window mode:

![screen shot 2015-05-09 at 4 25 11 am](https://cloud.githubusercontent.com/assets/261579/7548500/7a8d9bb8-f603-11e4-92e7-733954281982.png)

And this is what it looks like, largely duplicating the Glyph Edit window's `Chooser` panel:

![screen shot 2015-05-09 at 4 23 56 am](https://cloud.githubusercontent.com/assets/261579/7548497/402582f6-f603-11e4-817f-5488fb3ac79d.png)

I suggest that an `Actions` area be added to the end of the table of glyphs in the `Chooser` with the contents of the `import svg` window, and the import svg window removed. Also the import button could be at the top, which would expand to show the import details, so that its not "lost below the fold"

I think retaining a 'Import SVG' item next to 'Export' could be okay, but I thin it clutters the main menu with something that is more contextual and infrequently used; if retained, it would take the user to the Chooser, scrolled down (or with import expanded if at the top)

**Comment by mattlag** [comment]
Reviewing old ideas.  Closing this one because now you can simply drag+drop svg files onto the edit canvas for any character.
