### ISSUE TITLE
Multi Glyph Edit

### ISSUE THREAD

**Issue by pathumego** [glyphr-studio/Glyphr-Studio-1#197]
Multiline and multiple glyph editing would be awesome! Currently FontForge can edit multiple glyphs in a single line. But not multiple lines. Looked around to see if there ia an open issue. Didn't see anything. 

Here is how its done in glyphs app.https://www.youtube.com/watch?v=YN5-n9s9sAE&feature=youtu.be

And following is from a FontForge proposal doc

SCENARIO 1 - Load wordlists
- User opens the glyph window
- Loads a Multiline text file with wordlists
- FF will Show all the words from the text file in Multiple lines.
- Pathum Can edit glyph switching between the lines as same as within the line

SCENARIO 2 - Typing in (Option 1)
- User opens the glyph window
- Types in Multiple characters in the Input area.
- After 5-8 characters FF will automatically break the line and display rest in the next line.
- User Can edit glyphs switching between the lines as same as within the line

SCENARIO 2 - Typing in (Option 2)
- User opens the glyph window
- Types in Multiple characters in the Input area.
- Hit Enter to Break Lines
- Enter will add a special character to mark the line break. Or add a divider to the test area.
- Pathum Can edit glyphs switching between the lines as same as within the line

SCENARIO 2 - Typing on the canvas (Ideal Option) 
- Similar to Glyphs functionality, see a video of this at http://youtu.be/YN5-n9s9sAE
- User opens the glyph window
- Select the Multi Line tool next to the text input bar.
- It lets you type in like a simple text tool, on the drawing canvas itself you just type in your text
- Hit Enter to Break Lines
- Once done, switch back to drawing tools.
- Pathum Can edit glyps switching between the lines as same as within the line

Layout edit
- Design a separate  new window called Document Edit Window
- Have a preset Document Layout with sample text
- Users can select the language and it will load text
- Then users can zoom in and edit glyphs

**Comment by pathumego** [comment]
@mattlag any thoughts on this? Is this in your list :)

**Comment by mattlag** [comment]
Yes, I am definitely considering this.  It seems like the next logical step after #6 - just having the ability to *view* glyphs in the context of other glyphs.  Once this functionality is in place, it will be easy to add things like inline kern editing, or just plain editing.

My rough schedule for the time being is Multi-Select Shapes, then Boolean Features, then View Glyph with Other Glyphs Around It (#6)

**Comment by pathumego** [comment]
@mattlag Let me know when you start work on it :) I have some ideas after suffering from lack of UI features in fontforge. :)

**Comment by mattlag** [comment]
Okay - I will :-) finishing up v1.02 - I had thought of doing Boolean Combine features for v1.03, but #6  and this may be more fun.
