### ISSUE TITLE
Merge another project / font with the current one

### ISSUE THREAD

**Issue by mattlag** [glyphr-studio/Glyphr-Studio-1#223]
have to handle
- [ ] choosing a subset of glyphs to import
- [ ] glyph collisions, choosing between two glyphs with data
- [ ] upstream and downstream component chains

**Comment by polarathene** [comment]
I'd really love to see this feature :) It's an odd use case but I've recently been configuring my terminal and it would be great if I could take a font that I'd use and combine/add icon glyphs from another font and edit where neccessary, then export the font with new glyphs without concern of ruining the hinting data and such from the original font. 

If you've ever heard of Powerline it is one case where this is useful for patching a font, though I'd like to add a few glyphs beyond the ones Powerline uses for some theme code.

**Comment by mattlag** [comment]
Closing all v1 issues that will be addressed in v2.
