### ISSUE TITLE
Cannot import SVG created in Glyphr Studio

### ISSUE THREAD

**Issue by Autre31415** [glyphr-studio/Glyphr-Studio-1#247]
I discovered this while working on https://github.com/glyphr-studio/Glyphr-Studio-Desktop/issues/10.

If you start a project in Glyphr, export that project to SVG format and then attempt to import that SVG the import will fail. In my case with error: 'Unrecognized path command M78, ignoring and moving on'

I thought at first this was an issue with electron but I attempted the same steps using online Glyphr and happened upon the same issue. When this happens the app locks up completely and you have to close/refresh.

To reproduce this create a quick Glyph, export it to SVG and then attempt to import that SVG from the app landing page.

**Comment by mattlag** [comment]
Well, that's not good.  I have another SVG bug i'm looking into, so i'll look at this too.  M78 is definitely a valid path command... but since I wrote the SVG parser myself, there's probably an issue with it :-)

**Comment by Autre31415** [comment]
I tried a few more time making different random Glyphs and I'd get the error for different path commands each time, just to rule out the specific Glyph I had made.

Were you able to reproduce the error as well?

**Comment by mattlag** [comment]
Hey, this is fixed in v1.07.07 - try it out and let me know if you run into the same issue.
