### ISSUE TITLE
Rotation tool is off

### ISSUE THREAD

**Issue by mechanicious** [glyphr-studio/Glyphr-Studio-1#251]
Here you can see that the shape isn't back to it's initial rotation, after it is rotated by 360 deg with the rotation tool. 

I guess the simplest way to cause this issue would be to use rounded numbers for display but not for point coordinates.

![](http://imgur.com/QF3qYyD.gif)

**Comment by mattlag** [comment]
As a general rule I do math and store variables at full precision (whatever that is, like 9 places or something?) but only round to 3 when I show values to the user (1 on the canvas readout).  So you may be right... it may actually be 0.0002893034 or something.

**Comment by mattlag** [comment]
It's strange, I can't get it to sit at 0 degrees at all - now I think this is some sort of zero degree math bug...

**Comment by mechanicious** [comment]
Could be actually a combination of both. But either way, you should round up to the value you display even for the coordinates.

**Comment by mattlag** [comment]
Actually I am able to get 0 degrees... but it's a bit more complicated.  All the math is done in radians, so 0 degrees is actually PI/2... so it's not a math issue (although 90 degrees is zero radians, there still may be a math issue but not where I thought)

It's complicated by the fact that i'm actually rotating the shape while the user rotates the handle (as opposed to faking it then applying a final rotation once the user let's go of the rotation handle).  I'm back to thinking it's a rounding error... but it should "snap" back to certain points as opposed to snapping slightly off like it's doing now.

At any rate - kind of an edge case... Rotating 0 degrees is not very interesting :-)

**Comment by mechanicious** [comment]
The problem isn't just with 360 deg rotation; the rotation tool is off in general (for any rotation).

**Comment by mechanicious** [comment]
![](http://imgur.com/FfsHkVk.gif)

**Comment by mattlag** [comment]
Aha - I see now.  Fast mouse movements are compounding rounding errors.  I think the fix for this is to use a fake shape while showing the rotation preview... or save a copy of the original unrotated shape.  The preview shape could also reference the original unrotated shape on each mouse movement.  Then, do the "real" rotation against the original shape with the final angle.

Right now the frame of reference for 'this' rotation is the last rotation, not the original shape.  Thus allowing for compounded rounding errors.

**Comment by mechanicious** [comment]
![](http://i.imgur.com/n2AFOgF.jpg)

**Comment by mattlag** [comment]
fixed in 1.13.02
