### ISSUE TITLE
Retina support

### ISSUE THREAD

**Issue by loominade** [glyphr-studio/Glyphr-Studio-1#253]
on a retina display, half the application (the important part 😅) is blurry and does not use the available resolution.  

![sharp-vs-blurry](https://cloud.githubusercontent.com/assets/11677380/24997795/2c0413bc-2038-11e7-847d-de38dc782374.png)

**Comment by mechanicious** [comment]
@mattlag The issue here that the canvas is blurry. Can be reproduced on a PC by 1. let the canvas by drawn 2. set canvas width to less or more than 100% .
