### ISSUE TITLE
"Bulk transform glyph shapes" also transforms parent glyphs

### ISSUE THREAD

**Issue by rossjrw** [glyphr-studio/Glyphr-Studio-1#257]
### Issue

When bulk transforming a glyph that has elements pasted into it from another glyph, the parent glyph is also transformed.

### Reproduction

Create a character in any glyph.
Enter a blank glyph.
In the blank glyph, select "Get Shapes" then select the first glyph.
In the was-blank glyph, change the values under "bulk-transform glyph shapes".
The transformations are also applied to the source glyph.

### Expectation

The transformations specified in the paste-destination glyph should not be applied to the paste-source glyph.

**Comment by rossjrw** [comment]
Update: Hitting "Undo" will prevent this behaviour (ie cut all ties between the source and the destination) however this will not undo the Get Shapes action, which is the expected behaviour of Undo.

**Comment by mattlag** [comment]
Oh, that is a bug - i'll look into it.

**Comment by mattlag** [comment]
This only happens if there are no edits between the "Get Shapes" and bulk transform.  Any edit seems to break the link...

Definitely a bug, looking into it now.

**Comment by mattlag** [comment]
Will be fixed in v1.07.10 - thanks for filing the bug!
