### ISSUE TITLE
Cannot set x or y values to zero in attributes.

### ISSUE THREAD

**Issue by AnastasiaDunbar** [glyphr-studio/Glyphr-Studio-1#258]

**Comment by mattlag** [comment]
Hi @AnastasiaDunbar - can you provide more details?  What browser are you using? Currently I can set any value to 0 in the attributes panel.

Thanks!

**Comment by AnastasiaDunbar** [comment]
I'm using Firefox.

**Comment by mattlag** [comment]
I tested this on Win10 - Chrome / Firefox / Edge, and it all works.  Are you not using the most recent version of one of these browsers?  Are you on Mac?

**Comment by AnastasiaDunbar** [comment]
I'm on Win10 and I use the recent version, here's a GIF:
![test](https://user-images.githubusercontent.com/11806048/29880556-a39ecd12-8dda-11e7-9f88-b0fcb4c3322b.gif)

**Comment by mattlag** [comment]
You know what, I don't know what kind of crazy pills I was taking before - you are totally right.  I'm showing the same bug on my end as well.

I'm in a bug fixing mode, so this should be fixed soon.  But, as a workaround, you can set that value to .0001 (at least 3 zeros) and it will round it to 0, which seems to stick.

Thanks for working with me on this!

**Comment by mattlag** [comment]
Fixed in v1.08, will be released soon.  Thank you for the bug!
