### ISSUE TITLE
Do not allow special characters in metadata

### ISSUE THREAD

**Issue by mattlag** [glyphr-studio/Glyphr-Studio-1#273]
It breaks SVG, specifically & but probably others

**Comment by jackhumbert** [comment]
Would this affect ligatures not working after converting an SVG font to OFT? I've been unable to get `.` or `'` to work, but alphas have no issue. Both still show up in the `liga` look-up table.

**Comment by mattlag** [comment]
I think this is a separate issue - since SVG is an XML language, if you try to use certain characters in strings (like &) the XML document fails validation:

![image](https://user-images.githubusercontent.com/5897669/43602230-39bf7400-9644-11e8-9cbd-20fe9f828aba.png)

Converting ligature information from SVG to OTF... if some regular characters are converted but ligatures are not, it **doesn't** seem like metadata would be causing that.

(in a totally side note, Glyphr Studio will soon support direct export for Ligatures to OTF, without going through SVG first, it's what i'm working on now 😃 )

**Comment by jackhumbert** [comment]
Ah, gotcha! Thanks :) That's Glypher-Studio-2, right?

**Comment by mattlag** [comment]
Hey @jackhumbert  i've been thinking about your comment... I haven't specifically tested XML special characters as Ligatures... but it should "just work" because ligatures are specified in SVG using code points, not text:

![image](https://user-images.githubusercontent.com/5897669/43611394-d5e93c4e-965d-11e8-9e2d-51fa257138f6.png)

When you say they show up in the `liga` lookup table, are you using something to open up the resulting OTF file (like TTX)?  Maybe there is something odd with the OTF spec that doesn't allow some characters to be parts of Ligatures?  Another possible issue with SVG to OTF conversion is that it's a process outside of Glyphr Studio, so I can't control it - there may be some bug in whatever code is doing the conversion.

**Comment by mattlag** [comment]
Ligatures were recently added to OpenType.js, so I may just throw it into Glyphr-Studio-1 😃 A lot of the infrastructure is already in place.

Glyphr-Studio-2 is still very rough and probably a long way off from being in Beta.

**Comment by jackhumbert** [comment]
[This is the font I've been messing with](https://github.com/jackhumbert/zbalermorna-upright-font) - the ligatures that don't work in OTF are `.ia` and `.i'`. My process right now is to export via SVG, then convert to OTF via something like [this](https://cloudconvert.com/svg-to-otf) - I'm unsure of the quality of the conversion, or if there's a better, more complete way. 

I'm using Font Forge to inspect the GSUB lookups in the resulting OTF font. I could see something being weird with the spec, but the TTF files seem to have the same issue, and I've checked out the Kira font's lookups, which declare all sorts of tables, with various symbols. I'm not sure if certain tables are needed for certain replacements like that.

Ligature exports with OTF in GS1 would be awesome! I had the [pull request that added them to opentypejs marked](https://github.com/nodebox/opentype.js/pull/200), but saw that you had already upgraded to the latest version of it in GS2 :)
