### ISSUE TITLE
Support for non-BMP ranges (Emojis)

### ISSUE THREAD

**Issue by mattlag** [glyphr-studio/Glyphr-Studio-1#274]

**Comment by ErmineII** [comment]
I second this, and it's not just for emojis, also e.g. double-struck letters. I suggest, until support is added, to warn the user. I tried to make some characters which displayed as "HIGH SURROGATE PAIR $$$" "LOW SURROGATE PAIR $$$", but when I added a ligature with only the double-struck character, it seemed to work but failed on export.

**Comment by mattlag** [comment]
This actually sounds like a bug... I know there are many places in the code where I try to validate Unicode input and filter out stuff above U+FFFF  but it sounds like I missed something with Ligature creation.  I'll look into it - thanks!

**Comment by mattlag** [comment]
#320 has been fixed. For this more general issue, I'm putting all BMP+ feature ideas into Glyphr Studio 2, so I'm closing this one for Glyphr Studio v1.  Too many areas within V1 assume BMP, which is one of the major improvements v2 addresses.
