### ISSUE TITLE
<!-- ligature causes UI issues

### ISSUE THREAD

**Issue by ndaoust** [glyphr-studio/Glyphr-Studio-1#281]
Specifically, numeric text fields don't appear for that ligature, so it's impossible to set an absolute width or position elements precisely.

(This also applies to any ligature that starts with `<!--`, not that they'd see any use.)

**Comment by mattlag** [comment]
Oh, interesting. I will have to HTML escape the name of the ligature when rendering the UI... there are probably some other names that may cause issues too.

Problem understood, I'll look into fixing it tomorrow.

**Comment by mattlag** [comment]
Hi @ndaoust!

Wanted to let you know I fixed the <!-- issue in the latest commit:
https://github.com/glyphr-studio/Glyphr-Studio-1/tree/929fe08f31f6d8070a5adec40ec35d5d3aa0a1d5

It may be a week or two before I get around to building this into a release, but you can use this commit in the mean time.  Let me know if you have any questions!

**Comment by ndaoust** [comment]
I was able to make the `<!--` ligature and export it, but when I use the font, that particular ligature doesn't work.
