### ISSUE TITLE
Ligatures cannot start with '0'

### ISSUE THREAD

**Issue by ndaoust** [glyphr-studio/Glyphr-Studio-1#282]
Two-characters ligatures starting with `0`, such as `0x`, are refused. More characters and they're glitchy.

**Comment by mattlag** [comment]
You are finding all the good Ligature bugs :-D

**Comment by ndaoust** [comment]
Yeah there's a pattern here :-D

**Comment by mattlag** [comment]
Easy fix, just pushed the commit:
https://github.com/glyphr-studio/Glyphr-Studio-1/tree/c1d1c534de81701f303373d6832a1e2b6a92bc9d
