### ISSUE TITLE
Ligatures Break when Exported

### ISSUE THREAD

**Issue by Witch-y** [glyphr-studio/Glyphr-Studio-1#284]
Hello.
I'm having trouble getting ligatures to work on my font. When I export to .otf, every character that should be a ligature becomes one of four other characters instead of being the proper ligature. When I export to .svg, the ligatures do not appear at all. Everything works as it should on Test Drive.
[Here is my project file.](https://github.com/glyphr-studio/Glyphr-Studio-1/files/2609188/FoU.-.Glyphr.Project.-.2018.11.21-19.22.40.txt)

I've used Glyphr Studio for similar purposes before, and I haven't had any problems with my ligatures when exporting to .svg, so I don't know what's going wrong.

**Comment by Witch-y** [comment]
I managed to fix the ligatures by using FontForge to rename the glyphs from "Ligature X" to "X", to specify which ligatures should replace which source glyphs, and to change the export type to OpenType instead of Apple.

**Comment by mattlag** [comment]
Abugida - nice :-) I will take a look at what's going on. Today is a holiday so I may not get to it soon.  In the mean time, could you give me a bit more information?  What program are you using to test your ligatures (Microsoft Word / Adobe Illustrator / etc) and what exact sequences are failing (like ba, only a is showing).

The ligatures should just work straight from Glyphr Studio without modification, so i'd like to figure out what's going wrong.  Thanks for telling me about the issue!

**Comment by Witch-y** [comment]
I'm using AbiWord, LibreOffice, and [font dragr](http://labs.thecssninja.com/font_dragr/) to test the ligatures. I'm on Debian.
Any consonant-vowel sequence ligature fails: any of pbtdkgfvszxq combined with any of iaou results in only the vowel appearing or the consonant appearing as a different font, with the vowel following as a separate character. Something supposed to look like [this](https://user-images.githubusercontent.com/29666024/48921606-731aa100-ee66-11e8-99c2-a7af0b44a7e2.png) looks like [this](https://user-images.githubusercontent.com/29666024/48921612-8168bd00-ee66-11e8-8ec1-57fcc017e0aa.png).



Thanks for your help!

**Comment by mattlag** [comment]
Hello!  It's been a while, but I believe this has just been fixed in v1.13.07 - let me know if it hasn't and we can re-open the issue.  Thanks!
