### ISSUE TITLE
Ligatures Chooser pane doesn't recognize glyph ranges as being selected

### ISSUE THREAD

**Issue by QuasarQ** [glyphr-studio/Glyphr-Studio-1#285]
Despite having the default glyph range selected under Font Settings, the Ligature Chooser pane continues to display error message:

"**whoops!**
Looks like you don't have any glyph ranges enabled.
Go to Font Settings to enable Glyph Ranges."

Also tried adding Runic (for a random test) glyph range with no effect.

New ligatures can be created, but the Chooser pane continues to only show the error message, meaning that you cannot return to any ligature to edit it (though any created ligatures work in the test drive).

**Comment by mattlag** [comment]
Oh! That's a regression from yesterday's release. I'll fix it soon, thanks!!

**Comment by mattlag** [comment]
Issue is fixed, thank you for letting me know about the bug!

**Comment by QuasarQ** [comment]
Yay! I can edit my ligatures now!

Thank YOU! :smile:
