### ISSUE TITLE
Scroll bar missing

### ISSUE THREAD

**Issue by Nene-efo** [glyphr-studio/Glyphr-Studio-1#290]
I am using the software on a windows 8.1 PC. The screen resolution is 1366 x 768. The issue I have is that the right side of the interface has no scroll bars and thus I cannot access the functions lower then the screen area. I have hidden my taskbar, use the software in both maximum and minimum mode and still the issue persists.
I have attached a screenshot of the issue for your perusal.

Let me say congratulations for this software. As a novice, I am able to edit fonts and use them in my projects. I am grateful.
Sincerely, 
Nene-efo Obed
![Glyph](https://user-images.githubusercontent.com/26671750/56539754-b2a50080-655e-11e9-8be2-247f9d0343cc.png)

**Comment by mattlag** [comment]
Hello!

So, there aren't any scroll bars :-) do you not scroll with the mouse wheel, or touch pad on a laptop?

**Comment by Nene-efo** [comment]
Yes there are no scroll bars to all functions that shows on the right. For the main interface where you edit or design the font, it works perfectly. However the sections I added in my initial comment do not have scroll bars.

**Comment by mattlag** [comment]
Right - how it's design is that the panel on the left area has a scroll bar, but the page on the right does not have a scroll bar (even though the content scrolls).  So I know it's odd, but you should be able to scroll some way without the scroll bar visible, right?
