### ISSUE TITLE
cannot load ligatures from .otf or .ttf

### ISSUE THREAD

**Issue by Fenzland** [glyphr-studio/Glyphr-Studio-1#293]
I tried to drag a font with ligatures, into glyphr studio. Characters are loaded successfully, but none ligature is loaded.

I've tried with both online and desktop (both Linux and Windows), with font [FiraCode](https://github.com/tonsky/FiraCode).

**Comment by mattlag** [comment]
Hello!

Unfortunately, we do not import ligatures, or kern information from OTF files.  We do import them from SVG Font Files, so if you really need to import them, use an online font converter to first convert from OTF to SVG, then import to Glyphr Studio.

A more detailed look at importing / exporting can be found here:
http://help.glyphrstudio.com/overview_file_formats.html

I created issue #294  to track this idea, though I don't know when i'll be able to do it.

**Comment by mattlag** [comment]
Implemented in Glyphr Studio v2
