### ISSUE TITLE
"A" breaks on OTF export

### ISSUE THREAD

**Issue by michaelbrawn** [glyphr-studio/Glyphr-Studio-1#311]
There appears to be an issue with Glyphr Studio importing or exporting this font that makes some change to the capital "A" glyph. 

Steps to reproduce:
1. Open Print Clearly Font (http://www.bvfonts.com/fonts/details.php?id=45)
http://www.bvfonts.com/fonts/files/print_clearly.zip 

2. Export as OTF Font

Expected Behavoir:
No Change to Glyphs
![image](https://user-images.githubusercontent.com/3956938/85177533-4ef19280-b24a-11ea-8889-999d2fd2b1ff.png)

Actual Behaviour:
"A" Glyph is "less bold" than the original glyph. 
![image](https://user-images.githubusercontent.com/3956938/85177548-54e77380-b24a-11ea-8181-025054f611ed.png)

**Comment by mattlag** [comment]
Odd, seems fine when I do this on Windows... Did you actually install the font?  Sometimes the font previewer doesn't do a great job of previewing...

_Windows font preview_

![image](https://user-images.githubusercontent.com/5897669/85179145-0b405e00-b235-11ea-8f0d-9853ccbda4b2.png)

_Installed and working in Word_

![image](https://user-images.githubusercontent.com/5897669/85179204-3925a280-b235-11ea-9847-ae3aa0440fff.png)

**Comment by mattlag** [comment]
Regular weight looks fine too

![image](https://user-images.githubusercontent.com/5897669/85179347-96b9ef00-b235-11ea-930b-06e90064e2e0.png)

**Comment by michaelbrawn** [comment]
Weird. I tried rebooting and using Firefox on Mac OS Catalina 10.15.5 (19F101). 

Same issue with Print Clearly
`print_clearly/Open Type/print_clearly_ot.otf`
![image](https://user-images.githubusercontent.com/3956938/85180965-c9261500-b252-11ea-988a-080c18a07b5c.png)

No issue with Print Clearly Bold
`print_clearly/Open Type/print_bold_ot.otf`
![image](https://user-images.githubusercontent.com/3956938/85181248-6b45fd00-b253-11ea-8a30-c3923bd347ef.png)

I'll try on Windows when I have a chance.

**Comment by mattlag** [comment]
Would you do me a favor and send me the OTF that Glyphr Studio generated, the one with the strange A?  I can open it with some other tools (FontForge, or TTX) to see if it's a problem with the OTF itself.  Also, if you send me a file that looks bad on a mac, and it looks fine on Windows, then something else may be going on.

**Comment by michaelbrawn** [comment]
Thanks @mattlag. Here's the exported font and the project file. 
[Archive.zip](https://github.com/glyphr-studio/Glyphr-Studio-1/files/4808310/Archive.zip)

**Comment by michaelbrawn** [comment]
It looks like the space character is also set to an em unit size of 0 when importing the font. Would this be a separate issue?

**Comment by mattlag** [comment]
Hello!  Looking back through old Issues... the space import size of 0 is actually a bug I discovered in the OpenType.js library we use.  I filed a bug with them, but for the moment some font files do not have character advance widths imported correctly.
