### ISSUE TITLE
Ligatures do not export into "OTF" file formats.

### ISSUE THREAD

**Issue by ghost** [glyphr-studio/Glyphr-Studio-1#314]
Hey there! I've been working on an abugida font that has a ton of ligatures in order for the vowel glyphs to adapt and attach themselves onto the consonant glyphs. I think, in total, there are around 121-130 ligatures. I've worked on the font for around 8+ hours and still can't figure out why the ligatures aren't exporting to the otf file.

I've tried restarting my computer, I've also tried restarting glyphr and even reinstalling it, and even tried using the website version, however; none of these potential solutions have worked for me. In the exporting window it says it's exporting all of the ligatures, however; this is not the case as I go to type in my word processor nothing works at all and the vowel and consonant symbols remain in their static forms.

I was just wondering if there was any way to sort of "fix" this issue on my end because I don't know if this is a client side, or application/server side error on my part. But any kind of clarity would help a ton!

My font file, the way the font is supposed to look like, and the way the font currently looks like are shown below. Let me know if you can find out the reason for this, I've tried emailing, but unfortunately I haven't been able to get through to anyone, so I thought it would be a good idea to post this here.

[My Font - Glyphr Project - 2020.7.10-19.13.49.txt](https://github.com/glyphr-studio/Glyphr-Studio-1/files/4908020/My.Font.-.Glyphr.Project.-.2020.7.10-19.13.49.txt)
![should be](https://user-images.githubusercontent.com/68144140/87239180-bb872980-c3d1-11ea-9681-78ca58944bb3.png)
![currently](https://user-images.githubusercontent.com/68144140/87239183-bde98380-c3d1-11ea-992c-55ce34082e4d.png)

**Comment by VillaticLang** [comment]
Note: I've tried kerning and that didn't work either. Well, it did, but it displayed the wrong characters for some reason.

**Comment by mattlag** [comment]
Hello! I replied to your email - and I will look further into this issue when I'm back from vacation.  Thanks!

**Comment by Davequinnf** [comment]
Hi, @VillaticLang I tried to export your attached project and it works fine on my pc. Although it has some bad overlap rendering in windows font preview, my software process your ligatures without problems. What editor are you using? Have you tried it in different ones?

To the kerning issue - note that you can't kern ligatures in glyphr. Only individual letters to other letters. You would have to use something like FontForge to do that.

**Comment by VillaticLang** [comment]
I've been using microsoft word as google docs doesn't allow me to use my
font.

I don't particularly know where to find any other word processors. Could
you point me in the right direction?

**Comment by Davequinnf** [comment]
Ligatures are supported in MS Word but are turned off by default. Click on the settings in the font section (or CTRL+D), then navigate to the "advanced" tab and you'll see OpenType features where you can change ligatures settings. Just be aware that some other apps don't support ligatures at all. If you still won't be able to make it work in MS Word you can try LibreOffice where I tested your font without problems.
