### ISSUE TITLE
Characters not appearing even though there already made?

### ISSUE THREAD

**Issue by AydenC** [glyphr-studio/Glyphr-Studio-1#319]
Hi there, sorry, I was not able to write a description because my computer was being a d***.
Anyways, quite a problem as a title suggests... For example, as provided in the screenshot below; I've made the euro sign, but when I exported the font, it does not show up or work anywhere and I don't know why.
![Euro sign made but not there](https://user-images.githubusercontent.com/18643528/92183231-ac5ab000-ee45-11ea-8a74-14ccfb345912.png)
Oh, another thing that's annoying me a bit is that after I used the Glyphr Studio Desktop App, it seems as if the metadata has two versions of the extact same font (as provided in the second screenshot below.)
![Two regulars](https://user-images.githubusercontent.com/18643528/92183308-eb890100-ee45-11ea-9709-87f5f0492a13.png)
If you can fix this, then that will be great. Otherwise, I'll have to start over and that's the last thing I want.
Let me know if anything happens, many thanks!
- Ayden

**Comment by mattlag** [comment]
For the first Euro question, I quickly added a design to a project and exported it.  The Euro sign appeared as expected (it's the last one in the grid). 
![image](https://user-images.githubusercontent.com/5897669/92262067-66c2d500-ee8f-11ea-9cbd-9a00a4c973bd.png)

In your image you are pointing to the right spot.  Would you send me your Glyphr Studio Project File (.txt) and I can take a look to see if something strange is going on?

For your second issue - if you're installing the same font multiple times, but are making small changes each time, the OS may see these as part of the same family.  You may need to totally uninstall all previous versions of your font before installing a new version of it.  On windows you can go to this folder to see how many instances of your font you have installed, and manually delete fonts:
`C:\Windows\Fonts`
