### ISSUE TITLE
[Question] How to view/edit stylistic alternatives in GlyphrStudio

### ISSUE THREAD

**Issue by TheHandsomeCoder** [glyphr-studio/Glyphr-Studio-1#329]
Hey folks, really impressed with GlyphrStudio!

I'm working with a font that includes stylistic alternatives. Specifically it lets me use a single story `a` character instead of the double story `a`. I can access these through the typography options on OSX.

![image](https://user-images.githubusercontent.com/1569604/143601772-390f992f-52fa-44a1-a9c9-a047d2c4d172.png)

Is it possible to use the glyphs from the stylistic alternatives in GlyphrStudio? I have looked through the help docs and settings and unfortunately nothing jumped out at me.

Any help would be hugely helpful! :)

**Comment by TheHandsomeCoder** [comment]
Yup that worked perfectly, I just fliped the unicodes and names on the glyphs in the glyphset and exported it. Am now seeing the correct `a` in Glypher Studio

![image](https://user-images.githubusercontent.com/1569604/144418672-48a1da10-1066-451a-ba48-86b46c75fac3.png)

Code Sandbox for those who may need to do something similar in the future -> https://codesandbox.io/s/heuristic-poincare-pmocz?file=/src/index.js

**Comment by mattlag** [comment]
Nice, glad it worked!  OpenType.js is fantastic at accessing and editing raw font file information.  Glyphr Studio is basically just a nice looking vector editor built on top of it :-)
