### ISSUE TITLE
[Q] Is there any way to increase font size?

### ISSUE THREAD

**Issue by dehghani-mehdi** [glyphr-studio/Glyphr-Studio-1#331]
I have 2 different fonts and I want to use them both in same application. the problem is one of them is one unit smaller than the other one. I mean `font A with size 10` is same as `font B with size 11` (visually).

Is there any way to increase font A size by 1 unit?

**Comment by mattlag** [comment]
Every font can decide how many Em units total their typeface is, and within that, various key metrics like cap height, x height, ascender / descender etc.  Two fonts may have the same overall Em size, but each of these sizes may be in different proportions to each other... so this may be a harder problem than you think.

But, if you are able to figure out the delta between the two fonts, you can take the smaller one, and open it in Glyphr Studio.  From the menu, go to Global Actions, and there is a "Resize All Glyphs" action that will loop through all the glyphs in that font and resize them.

![image](https://user-images.githubusercontent.com/5897669/155039614-7e75e9c9-62e4-45d3-bf18-76e6f64070c3.png)

There are *many* things that could end up wonky when you do this, so you'll also probably have to go through each character to see if it still looks good.  And, you may have to try it and export it a couple different times to get the proportions looking right.

Really, it's probably easier just to work with two different sizes in your application, as opposed to adjusting a whole font.  But, it is possible with a bunch of work to scale a whole font.

I'm going to close this, but let me know if you have any more questions!
