### ISSUE TITLE
Bug when fonts saving

### ISSUE THREAD

**Issue by diesel167** [glyphr-studio/Glyphr-Studio-1#337]
I spent a lot of time searching my mistake. But it seems that there is a mistake in the service. Please, try to open any font (.otf formatted) then do nothing and save it. Open Glyphr in new tab and import saved font there. "X" coordinate of every symbol will 20 points more than in original font, width will 20 points more too. What is going on? In the past it was good.

before saving
![Ashampoo_Snap_8 июля 2022 г _19h10m28s_018_](https://user-images.githubusercontent.com/42602312/178030610-aefab180-5b47-4b65-be6c-bb6708dac805.png)

open font after saving
 ![Ashampoo_Snap_8 июля 2022 г _19h10m33s_019_](https://user-images.githubusercontent.com/42602312/178030600-9942a5bf-4ce6-43c8-bb47-06c86168201a.png)
Also saved font looks bad in usage.

When i preview it before saving:
![Ashampoo_Snap_8 июля 2022 г _19h19m35s_020_](https://user-images.githubusercontent.com/42602312/178031487-5b64ba27-6e52-4b28-a3ff-53d44cfd2ee1.png)
After saving (and doing nothing before):
![Ashampoo_Snap_8 июля 2022 г _19h19m43s_021_](https://user-images.githubusercontent.com/42602312/178031576-3890a5f7-0970-4df0-bc05-3487f0d9752b.png)

UPD: if you import .ttf, not .otf and then export .otf - all looks fine.

**Comment by mattlag** [comment]
I'll take a look - Glyphr Studio has a feature for Automatic Side Bearings, which defaults to 20... They are supposed to be disabled when you import a font - so maybe they are being added when they shouldn't be.

**Comment by mattlag** [comment]
Looks like OpenType.js is giving NaN as the advance width when importing some fonts. When this happens, the "auto-calculate glyph width" is turned on, and by default there are side bearings applied (which is where the extra width is being added).

I'm doing further investigation to see about the import bug from OpenType.js

**Comment by mattlag** [comment]
I just pushed an updated version, v1.13.12 - refresh Glyphr Studio online, make sure the version number is correct, and see if you are still having the issue.
![image](https://user-images.githubusercontent.com/5897669/178052489-ebadeffe-91b3-494f-b005-484bad57001e.png)

**Comment by mattlag** [comment]
I believe this is fixed, let me know if not.
